<?php
namespace App\Http\Controllers\Student;
use App\Http\Controllers\Concerns\LogsActivity; use App\Http\Controllers\Controller; use App\Models\Claim; use App\Models\FoundItem; use App\Models\LostItem; use App\Models\TmcNotification; use App\Models\User; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\View\View;
class ClaimController extends Controller
{ use LogsActivity;
 public function index(Request $request): View { return view('claims.index',['role'=>'student','claims'=>Claim::with(['foundItem.category','reviewer'])->where('student_id',$request->user()->id)->filtered($request->all())->latest()->paginate(15)->withQueryString()]); }
 public function create(Request $request): View { return view('claims.create',['foundItems'=>FoundItem::where('status','unclaimed')->orderBy('title')->get(),'lostItems'=>LostItem::where('user_id',$request->user()->id)->orderBy('title')->get(),'selectedFoundItem'=>$request->found_item_id]); }
 public function store(Request $request): RedirectResponse { $data=$request->validate(['found_item_id'=>['required',Rule::exists('found_items','id')->where('status','unclaimed')],'lost_item_id'=>'nullable|exists:lost_items,id','claim_description'=>'required|string|min:30|max:1000','proof_image'=>'nullable|image|mimes:jpg,jpeg,png|max:2048']); $duplicate=Claim::where('student_id',$request->user()->id)->where('found_item_id',$data['found_item_id'])->where('status','pending')->exists(); if($duplicate){return back()->withErrors(['found_item_id'=>'You already have a pending claim for this item.'])->withInput();} if($request->hasFile('proof_image')){$data['proof_image']=$request->file('proof_image')->store('claim-proofs','public');} $claim=Claim::create($data+['student_id'=>$request->user()->id,'status'=>'pending']); TmcNotification::create(['user_id'=>$claim->foundItem->staff_id,'title'=>'New claim request','message'=>$request->user()->name.' filed a claim for '.$claim->foundItem->title.'.','type'=>'claim_update','link'=>route('staff.claims.show',$claim)]); User::where('role','admin')->get()->each(fn($admin)=>TmcNotification::create(['user_id'=>$admin->id,'title'=>'New claim request','message'=>$request->user()->name.' filed a claim for '.$claim->foundItem->title.'.','type'=>'claim_update','link'=>route('admin.claims.show',$claim)])); $this->logAction($request,'Filed claim #'.$claim->id,$claim); return redirect()->route('student.claims.index')->with('success','Claim submitted. Staff will review it.'); }
 public function show(Claim $claim): View { abort_if($claim->student_id !== auth()->id(),403); return view('claims.show',['role'=>'student','claim'=>$claim->load(['student','foundItem.category','lostItem','reviewer'])]); }
}
