<?php
namespace App\Http\Controllers\Student;
use App\Http\Controllers\Concerns\LogsActivity; use App\Http\Controllers\Controller; use App\Models\Category; use App\Models\LostItem; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\View\View;
class LostItemController extends Controller
{ use LogsActivity;
 public function index(Request $request): View { return view('items.lost-index',['role'=>'student','items'=>LostItem::with('category')->where('user_id',$request->user()->id)->filtered($request->all())->latest()->paginate(15)->withQueryString(),'categories'=>Category::orderBy('name')->get()]); }
 public function create(): View { return view('items.lost-form',['role'=>'student','item'=>new LostItem(['date_lost'=>now()]),'categories'=>Category::orderBy('name')->get(),'action'=>route('student.lost-items.store'),'method'=>'POST']); }
 public function store(Request $request): RedirectResponse { $data=$request->validate(['title'=>'required|string|max:150','category_id'=>'required|exists:categories,id','description'=>'required|string|max:1000','date_lost'=>'required|date|before_or_equal:today','location_lost'=>'required|string|max:255','image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:2048']); if($request->hasFile('image')){$data['image']=$request->file('image')->store('lost-items','public');} $item=LostItem::create($data+['user_id'=>$request->user()->id,'status'=>'lost']); $this->logAction($request,'Reported lost item '.$item->title,$item); return redirect()->route('student.lost-items.index')->with('success','Lost item reported.'); }
 public function show(LostItem $lostItem): View { $this->authorizeOwner($lostItem); return view('items.lost-show',['item'=>$lostItem->load(['user','category']),'role'=>'student']); }
 public function edit(LostItem $lostItem): View { $this->authorizeOwner($lostItem); return view('items.lost-form',['role'=>'student','item'=>$lostItem,'categories'=>Category::orderBy('name')->get(),'action'=>route('student.lost-items.update',$lostItem),'method'=>'PUT']); }
 public function update(Request $request, LostItem $lostItem): RedirectResponse { $this->authorizeOwner($lostItem); $data=$request->validate(['title'=>'required|string|max:150','category_id'=>'required|exists:categories,id','description'=>'required|string|max:1000','date_lost'=>'required|date|before_or_equal:today','location_lost'=>'required|string|max:255','status'=>['required',Rule::in(['lost','found','closed'])],'image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:2048']); if($request->hasFile('image')){$data['image']=$request->file('image')->store('lost-items','public');}else{unset($data['image']);} $lostItem->update($data); $this->logAction($request,'Updated lost item '.$lostItem->title,$lostItem); return redirect()->route('student.lost-items.index')->with('success','Lost report updated.'); }
 public function destroy(Request $request, LostItem $lostItem): RedirectResponse { $this->authorizeOwner($lostItem); $this->logAction($request,'Deleted lost item '.$lostItem->title,$lostItem); $lostItem->delete(); return back()->with('success','Lost report deleted.'); }
 private function authorizeOwner(LostItem $item): void { abort_if($item->user_id !== auth()->id(),403); }
}
